language: ruby
rvm:
- ruby-head
bundler_args: "--without production"
script:
- RAILS_ENV=test
- bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
deploy:
  provider: heroku
  api_key:
    secure: rj3+4HweLnrZ+cxWS7Xk0/bzTUeZT4x1P3OoUZWiB19Z+3nL/gK3ZiwEr3DD11Z3I8sEKc0wz7WmBKXKycgit+HQCejNZoGYKCIlxNwIzrNlWPWfrDqvgV5OuaeebjXLaVYs267S5UV1iXfoDtUwOd0Bs1gCmIJciG8ct4LdBx/7pD9fIHSAXsbUtD0H9GrFUrMtu3SfVNCY/q3uB/9cZokjJfRTAA1kl5Pn3Q5KuKuMl5u4u+R5KQaRpxa7ivouto6MN22QcR6N/uZxbTVjCQ2W58YGBHZiGFP9YzlyofQ38gle/DQSVJnGiNFzd1lnmO5jT9x+u1ReB2Vo43eW3Fi88MTe7MaNE5yNZIiHZzWYkz2JjEHYffULYJIotyre/kjumZj0zMSGUR3pnZh7a3KGnZKNhigXGJz4dQJOxN7pv3DnjahpfcV4DeYqBEveBqCdyMsQZc8JCMTH8vKoEIsz7xV7yibZ6pa8B0HjGwI7XoA3RTymlth2mShTfdSGMOHMtoHeGwAoIcU0u1usu1eDIPCwNqSBDONKRP7w3iUEsj7XQCizBUu7srGrPiiZ25Hm8+e5e0BGUJcgUfr1xHitGhQULd2inPgxrsM3MWFqj+NZPKWdP9M+YYKBtbeJBW1YmbSB38RxFHb3v6CY4NrpqsG8/4t7fwOb8vKNLX4=
  app: Novedades
  on:
    repo: matiasmasca/Novedades
